from .amiga import pack_planar
from .indexed import IndexedBitmap


def export_raw_planar(bitmap: IndexedBitmap) -> bytes:
    return pack_planar(bitmap)


def export_c(bitmap: IndexedBitmap, symbol: str = "asset") -> str:
    data = pack_planar(bitmap)
    values = ", ".join(f"0x{b:02x}" for b in data)
    palette = ", ".join(
        f"0x{r:02x}, 0x{g:02x}, 0x{b:02x}" for r, g, b in bitmap.palette
    )
    return (
        f"/* Generated by RetroAsset */\n"
        f"#define {symbol.upper()}_WIDTH {bitmap.width}\n"
        f"#define {symbol.upper()}_HEIGHT {bitmap.height}\n"
        f"#define {symbol.upper()}_PLANES {bitmap.planes}\n"
        f"static const unsigned char {symbol}_data[] = {{ {values} }};\n"
        f"static const unsigned char {symbol}_palette[] = {{ {palette} }};\n"
    )


def export_asm(bitmap: IndexedBitmap, symbol: str = "asset") -> str:
    data = pack_planar(bitmap)
    rows = []
    for offset in range(0, len(data), 16):
        rows.append("    dc.b " + ",".join(f"$%02x" % b for b in data[offset:offset + 16]))
    palette_words = []
    for r, g, b in bitmap.palette:
        word = ((r >> 4) << 8) | ((g >> 4) << 4) | (b >> 4)
        palette_words.append("$%03x" % word)
    return (
        "; Generated by RetroAsset\n"
        + f"{symbol}_width equ {bitmap.width}\n"
        + f"{symbol}_height equ {bitmap.height}\n"
        + f"{symbol}_planes equ {bitmap.planes}\n"
        + f"{symbol}_data:\n" + "\n".join(rows) + "\n"
        + f"{symbol}_palette:\n    dc.w " + ",".join(palette_words) + "\n"
    )
